# fly.toml app configuration file generated for mathlearn on 2023-11-25T19:01:49-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "mathlearn"
primary_region = "gru"
console_command = "php /var/www/html/artisan tinker"

[build]
  [build.args]
    NODE_VERSION = "18"
    PHP_VERSION = "8.1"

[env]
  APP_NAME = "Mathlearn"
  APP_ENV = "local"
  APP_DEBUG = true
  LOG_CHANNEL = "stderr"
  LOG_LEVEL = "info"
  LOG_STDERR_FORMATTER = "Monolog\\Formatter\\JsonFormatter"
  SESSION_DRIVER = "cookie"
  SESSION_SECURE_COOKIE = "true"
  DB_CONNECTION = "pgsql"
  DB_HOST = "dbmathlearn.fly.dev"
  DB_DATABASE= "mathlearn"
  DB_PORT = 5432

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
